name: awesome_period_tracker
description: "An awesome period tracker app, because your cycle deserves a standing ovulation"
publish_to: "none"
version: 1.4.1+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: "3.27.1"

dependencies:
  animations: ^2.0.11
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  envied: ^1.0.0
  firebase_analytics: ^11.3.5
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  flutter:
    sdk: flutter
  flutter_emoji: ^2.5.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.3
  injectable: ^2.5.0
  intl: any
  json_annotation: ^4.9.0
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.0.1
  shared_preferences: ^2.2.3
  skeletonizer: ^1.4.2
  table_calendar: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^1.0.0
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/svgs/
    - assets/images/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/google_fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/DMSans-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#f9fafb"
  image: "assets/splash/app_icon.png"
  android_12:
    color: "#f9fafb"
    image: "assets/splash/app_icon.png"
