name: awesome_period_tracker
description: "A simple yet awesome period tracker app, because your cycle deserves a standing ovulation"
publish_to: "none"
version: 1.0.6+1

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  animations: ^2.0.11
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.2.2
  envied: ^0.5.4+1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  flutter:
    sdk: flutter
  flutter_emoji: ^2.5.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.3
  intl: any
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.0.0
  pinput: ^5.0.0
  shared_preferences: ^2.2.3
  skeletonizer: ^1.4.1+1
  table_calendar: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/svgs/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/google_fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/DMSans-Bold.ttf
          weight: 700
