name: Create release
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm_config

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm_config.outputs.FLUTTER_VERSION }}

      - name: Configure Firebase
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS }}" | base64 --decode > lib/core/firebase_options.dart
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json

      - name: Configure environment
        run: echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Download dependencies
        run: flutter pub get

      - name: Run build runner and generate localization files
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter gen-l10n

      - name: Build Android
        run: flutter build apk --release --build-number=${{ github.run_number }} --split-per-abi

      - name: Upload Android build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-artifacts
          path: build/app/outputs/flutter-apk/*.apk

  build-ios:
    name: Build IPA
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - uses: actions/checkout@v3

      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm_config

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm_config.outputs.FLUTTER_VERSION }}

      - name: Configure Firebase
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS }}" | base64 --decode > lib/core/firebase_options.dart
          echo "${{ secrets.FIREBASE_APP_ID_FILE }}" | base64 --decode > ios/firebase_app_id_file.json
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Configure environment
        run: echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Download dependencies
        run: flutter pub get

      - name: Run build runner and generate localization files
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter gen-l10n

      - name: Build iOS
        run: flutter build ios --release --no-codesign --build-number=${{ github.run_number }}

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app.ipa Payload

      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-artifacts
          path: build/ios/iphoneos/app.ipa

  create-release:
    name: Create Release
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Read latest version from CHANGELOG
        id: changelog
        shell: bash
        run: |
          LATEST_VERSION=$(grep -m1 "^## \[" CHANGELOG.md | grep -v "Unreleased" | sed -E 's/## \[(.*)\].*/\1/')
          CHANGELOG_CONTENT=$(sed -n "/^## \[$LATEST_VERSION/,/^## \[/p" CHANGELOG.md | sed '1d;$d')
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo 'content<<EOF' >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          prerelease: false
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "android-artifacts/*.apk,ios-artifacts/app.ipa"
          body: |
            ${{ steps.changelog.outputs.content }}

            Note: The IPA file is unsigned and intended solely for testing purposes. It is not eligible for App Store submission. Installation and execution on a device require a developer account and Xcode.
